Add Parse*Geometry methods
gographics/imagick pull request #304
Opened 2024-02-13 00:37 UTC by beetlebugorg

2024-02-13 02:00 UTC, justinfx requested changes

2024-02-13 02:00 UTC, justinfx commented on imagick/geometry.go
Could we copy over the docstrings for the public functions, like the rest of the API provides?

2024-02-13 02:11 UTC, beetlebugorg commented on imagick/geometry.go
Yes, I can do that.

2024-02-16 03:10 UTC, beetlebugorg commented on imagick/geometry.go
Are you asking for [these](https://github.com/ImageMagick/ImageMagick/blob/main/MagickCore/geometry.c#L1428-L1470) to be copied? I don't see that elsewhere.

These methods don't appear in their documentation but also don't appear to be considered private either. They're used by the `magick` (`convert` in IM6) to parse image geometry for resize and crop operations.

2024-02-16 03:13 UTC, justinfx commented on imagick/geometry.go
Yes that would work. Even if ImageMagick don't expose them in their public headers, if we are exposing exported functions and methods in our bindings, we want them to have docstrings to explain the usage. 
I usually just copy them over from the ImageMagick source or headers and sightly tweak whatever C references to match the Go params.

2024-02-16 12:43 UTC, beetlebugorg commented on imagick/geometry.go
Alright, copied over.

2024-02-16 19:56 UTC, merged